//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 06:27:43 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "www.xseam.org/schemas/Domain")
package org.xseam.domain;
