//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 06:27:43 PM BRT 
//


package org.xseam.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.xseam.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class StateObjectFactory {

    private final static QName _Dominio_QNAME = new QName("www.xseam.org/schemas/Domain", "domain");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.xseam.dominio
     * 
     */
    public StateObjectFactory() {
    }

    /**
     * Create an instance of {@link State }
     * 
     */
    public State createDominio() {
        return new State();
    }

    /**
     * Create an instance of {@link ItemState }
     * 
     */
    public ItemState createItem() {
        return new ItemState();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemState }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "www.xseam.org/schemas/Domain", name = "domain")
    public JAXBElement<ItemState> createDominio(ItemState value) {
        return new JAXBElement<ItemState>(_Dominio_QNAME, ItemState.class, null, value);
    }

}
